// Pin the timezone before any worker boots. Several components format dates for
// display, so without this the suite passes locally and fails on UTC CI (or the
// reverse) purely on the developer's machine settings.
process.env.TZ = 'UTC';

const nextJest = require('next/jest');

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
});

// Add any custom config to be passed to Jest
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testEnvironment: 'jest-environment-jsdom',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
  testMatch: ['**/__tests__/**/*.test.{ts,tsx}', '**/*.test.{ts,tsx}'],

  // Radix dialogs, react-day-picker and the debounced filter bar are slow to
  // mount under a loaded CI machine. The 5s default made whole suites flake
  // even though every assertion is deterministic.
  testTimeout: 20000,

  // Coverage is measured over the dashboard's own code. `components/ui/**` is
  // deliberately absent: those are shadcn primitives generated by
  // `npx shadcn add`, replaced wholesale on regeneration, and already covered
  // indirectly wherever the app renders them.
  collectCoverageFrom: [
    'app/**/*.{ts,tsx}',
    'lib/**/*.{ts,tsx}',
    'proxy.ts',
    // Type-only modules: they compile away to nothing, so istanbul reports them
    // as empty files and they only add noise to the report.
    '!lib/api/types.ts',
    '!lib/auth/types.ts',
    '!**/*.d.ts',
  ],
  coverageThreshold: {
    global: {
      statements: 90,
      branches: 90,
      functions: 90,
      lines: 90,
    },
  },
};

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
module.exports = createJestConfig(customJestConfig);
